# Generated by Django 5.0.4 on 2024-05-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_purchaseorder_quality_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
